Issue113: Refactoring InformationSheetContent file: 100% DONE
precision-sustainable-ag/dst-selector pull request #133
Opened 2022-09-27 18:18 UTC by dearpriyankasa

2022-09-27 18:31 UTC, drewlearns commented
Your review app has been deployed and is available at 'http://20.85.187.248:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

2022-09-27 18:32 UTC, drewlearns commented
Your review app has been deployed and is available at 'http://20.85.187.248:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

2022-09-27 18:44 UTC, mikahpinegar requested changes

2022-09-27 18:44 UTC, mikahpinegar commented on src/pages/InformationSheetContent/PlantingAndGrowthWindows/PlantingAndGrowthWindows.js
> +import MonthDayString from './getMonthDayString';
this should be getMonthDayString

2022-09-27 19:39 UTC, dearpriyankasa commented on src/pages/InformationSheetContent/PlantingAndGrowthWindows/PlantingAndGrowthWindows.js
> +import MonthDayString from './getMonthDayString';
Done

2022-09-27 19:53 UTC, drewlearns commented
Your review app has been deployed and is available at 'http://20.85.187.248:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

2022-09-27 19:54 UTC, drewlearns commented
Your review app has been deployed and is available at 'http://20.85.187.248:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

2022-09-28 15:51 UTC, mikahpinegar approved these changes

2022-09-28 16:38 UTC, merged