Feature/legacy data
precision-sustainable-ag/dst-selector pull request #258
Opened 2023-01-06 00:17 UTC by Adamws33

updated selector to use legacy data API for 
Sidebar categories
Sidebar filters
Sources
data-dictionary

2023-01-06 17:10 UTC, Adamws33 commented
> 

Done!

2023-01-09 14:55 UTC, mikahpinegar commented
comparison view in cover crop list is broken

2023-01-09 14:58 UTC, mikahpinegar commented
when going to cc list from explorer it shows no goals in comparison view, when coming from selector it only shows the goals selected by the user

2023-01-09 16:16 UTC, mikahpinegar commented
clicking on a crop to open info sheet makes approx 50 api calls to `/data-dictionary`

2023-01-09 16:19 UTC, mikahpinegar commented
the data dictionary should probably only be fetched once instead of in a bunch of places

2023-01-09 16:54 UTC, Adamws33 commented
> lot's of crops missing from `/data-dictionary` ex: barley winter, brassica forage in zone 6

This will have to be updated on the back end.  It sounds like there are things missing from the data in the database.

2023-01-09 16:57 UTC, Adamws33 commented
> the data dictionary should probably only be fetched once instead of in a bunch of places

i can implement that now but i thought since we were changing things soon to be more dynamic we were just focusing on getting it converted over from the local data to the API.  

same for the 50 calls on the infosheet call.  I noticed that im pretty sure its doing one call per crop to find the right one.  i figured it was best just to get this API working like it was before since its getting redone soon.

2023-01-09 20:51 UTC, mikahpinegar requested changes

2023-01-09 20:51 UTC, mikahpinegar commented on src/pages/CropSidebar/CropSidebar.js
> +  }, []);
this should trigger every time zone changes right?

2023-01-10 19:47 UTC, mikahpinegar approved these changes

2023-01-10 19:47 UTC, merged