Soil Conditions file refactoring
precision-sustainable-ag/dst-selector pull request #94
Opened 2022-09-12 01:46 UTC by dearpriyankasa

2022-09-12 18:20 UTC, mikahpinegar commented
unselecting the chips is broken for drainage class and flooding frequency

2022-09-12 18:24 UTC, mikahpinegar requested changes

2022-09-12 18:24 UTC, mikahpinegar commented on src/components/Location/SoilCondition/SoilCondition.js
> +                  if (e.target.checked) {
i think all this logic is broken

2022-09-12 18:26 UTC, mikahpinegar commented
i think only one chip should be selectable for flooding frequency and drainage class but i'll need to get clarification. for now just make it so the chips can be unselected and the broken logic above works properly

2022-09-12 19:14 UTC, dearpriyankasa commented on src/components/Location/SoilCondition/SoilCondition.js
> +                  if (e.target.checked) {
Okay, I'll take a look

2022-09-14 16:45 UTC, mikahpinegar approved these changes

2022-09-14 17:02 UTC, merged